### ISSUE TITLE
Türkçe için tureng bağlanması

### ISSUE THREAD

**Issue by abdurrahmanekr** [selmansamet/bascevir#1]
Bazan kelimenin diğer anlamlarını da öğrenmek istiyorum. Sadece türkçeye özel tureng'e bağlanabilir.

**Comment by sametcodes** [comment]
Talep için teşekkkürler :tada: 

Şuan Single API çalışıyor. Yani Google tek bir sonuç veriyor. Diğer kelime anlamlarını almak için kullanıcıların Google üzerinden API anahtarı alması gerekecek. Bunun için bir ayarları sayfası yapacağım. Eğer anahtar girilmemişse Single API'ya istek gönderilecek ve tek bir sonuç alınacak, anahtar girilmişse birden fazla anlam döndüğü için çıkan baloncuk içeriği birden fazla kelime içerecek.

Şuan yalnızca İngilizce-Türkçe çeviri çalışıyor. Sonraki versiyonlarda google çevirinin sunduğu tüm dillerde çalışması için düzenlemeler yapacağım. O noktada Tureng'in Google Çeviri'ye göre artılarını ele almak gerekir.

Kelime çevirileri için tureng ve diğer benzer çevrimiçi sözlüklere bağlantılar oluşturulabilir. Kullanıcı bir kaç tıkla bu sözlüklere ulaşım sağlayabilir :+1:

**Comment by sametcodes** [comment]
_Kişiselleştirilmiş sözlük_ özelliğiyle eklenebilir. Buradan devam edecek: https://github.com/selmansamet/bascevir/issues/2
